/* tslint:disable */
/* eslint-disable */
import { GraphQLResolveInfo } from 'graphql';
/**
 * This file is auto-generated by graphql-schema-typescript
 * Please note that any changes in this file may be overwritten
 */
 

/*******************************
 *                             *
 *          TYPE DEFS          *
 *                             *
 *******************************/
export interface GQLQuery {
  name: string;
  weather: GQLWeather;
}

export interface GQLWeather {
  location: GQLWeatherLocation;
  current: GQLWeatherCurrent;
}

export interface GQLWeatherLocation {
  name: string;
  region: string;
  country: string;
  latitude: number;
  longitude: number;
  timezone: string;
  timeEpoch: number;
  timeFormatted: string;
}

export interface GQLWeatherCurrent {
  temperature: GQLWeatherTemperature;
  feelsLike: GQLWeatherTemperature;
  condition: GQLWeatherCondition;
  wind: GQLWeatherWind;
  gust: GQLWeatherVelocity;
  pressure: GQLWeatherPressure;
  rain: GQLWeatherRain;
  humidityPercentage: number;
  cloudCoverPercentage: number;
  isDaytime: boolean;
  uvIndex: number;
}

export interface GQLWeatherTemperature {
  celsius: number;
  fahrenheit: number;
}

export interface GQLWeatherCondition {
  text: string;
  code: number;
  iconSrc: string;
}

export interface GQLWeatherWind {
  mph: number;
  kph: number;
  direction: GQLWeatherWindDirection;
}

export interface GQLWeatherWindDirection {
  degree: number;
  compass: string;
}

export interface GQLWeatherVelocity {
  mph: number;
  kph: number;
}

export interface GQLWeatherPressure {
  millibars: number;
  inches: number;
}

export interface GQLWeatherRain {
  millimeters: number;
  inches: number;
}

/*********************************
 *                               *
 *         TYPE RESOLVERS        *
 *                               *
 *********************************/
/**
 * This interface define the shape of your resolver
 * Note that this type is designed to be compatible with graphql-tools resolvers
 * However, you can still use other generated interfaces to make your resolver type-safed
 */
export interface GQLResolver {
  Query?: GQLQueryTypeResolver;
  Weather?: GQLWeatherTypeResolver;
  WeatherLocation?: GQLWeatherLocationTypeResolver;
  WeatherCurrent?: GQLWeatherCurrentTypeResolver;
  WeatherTemperature?: GQLWeatherTemperatureTypeResolver;
  WeatherCondition?: GQLWeatherConditionTypeResolver;
  WeatherWind?: GQLWeatherWindTypeResolver;
  WeatherWindDirection?: GQLWeatherWindDirectionTypeResolver;
  WeatherVelocity?: GQLWeatherVelocityTypeResolver;
  WeatherPressure?: GQLWeatherPressureTypeResolver;
  WeatherRain?: GQLWeatherRainTypeResolver;
}
export interface GQLQueryTypeResolver<TParent = any> {
  name?: QueryToNameResolver<TParent>;
  weather?: QueryToWeatherResolver<TParent>;
}

export interface QueryToNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QueryToWeatherArgs {
  location: string;
}
export interface QueryToWeatherResolver<TParent = any, TResult = any> {
  (parent: TParent, args: QueryToWeatherArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLWeatherTypeResolver<TParent = any> {
  location?: WeatherToLocationResolver<TParent>;
  current?: WeatherToCurrentResolver<TParent>;
}

export interface WeatherToLocationResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherToCurrentResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLWeatherLocationTypeResolver<TParent = any> {
  name?: WeatherLocationToNameResolver<TParent>;
  region?: WeatherLocationToRegionResolver<TParent>;
  country?: WeatherLocationToCountryResolver<TParent>;
  latitude?: WeatherLocationToLatitudeResolver<TParent>;
  longitude?: WeatherLocationToLongitudeResolver<TParent>;
  timezone?: WeatherLocationToTimezoneResolver<TParent>;
  timeEpoch?: WeatherLocationToTimeEpochResolver<TParent>;
  timeFormatted?: WeatherLocationToTimeFormattedResolver<TParent>;
}

export interface WeatherLocationToNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherLocationToRegionResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherLocationToCountryResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherLocationToLatitudeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherLocationToLongitudeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherLocationToTimezoneResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherLocationToTimeEpochResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherLocationToTimeFormattedResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLWeatherCurrentTypeResolver<TParent = any> {
  temperature?: WeatherCurrentToTemperatureResolver<TParent>;
  feelsLike?: WeatherCurrentToFeelsLikeResolver<TParent>;
  condition?: WeatherCurrentToConditionResolver<TParent>;
  wind?: WeatherCurrentToWindResolver<TParent>;
  gust?: WeatherCurrentToGustResolver<TParent>;
  pressure?: WeatherCurrentToPressureResolver<TParent>;
  rain?: WeatherCurrentToRainResolver<TParent>;
  humidityPercentage?: WeatherCurrentToHumidityPercentageResolver<TParent>;
  cloudCoverPercentage?: WeatherCurrentToCloudCoverPercentageResolver<TParent>;
  isDaytime?: WeatherCurrentToIsDaytimeResolver<TParent>;
  uvIndex?: WeatherCurrentToUvIndexResolver<TParent>;
}

export interface WeatherCurrentToTemperatureResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherCurrentToFeelsLikeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherCurrentToConditionResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherCurrentToWindResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherCurrentToGustResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherCurrentToPressureResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherCurrentToRainResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherCurrentToHumidityPercentageResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherCurrentToCloudCoverPercentageResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherCurrentToIsDaytimeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherCurrentToUvIndexResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLWeatherTemperatureTypeResolver<TParent = any> {
  celsius?: WeatherTemperatureToCelsiusResolver<TParent>;
  fahrenheit?: WeatherTemperatureToFahrenheitResolver<TParent>;
}

export interface WeatherTemperatureToCelsiusResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherTemperatureToFahrenheitResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLWeatherConditionTypeResolver<TParent = any> {
  text?: WeatherConditionToTextResolver<TParent>;
  code?: WeatherConditionToCodeResolver<TParent>;
  iconSrc?: WeatherConditionToIconSrcResolver<TParent>;
}

export interface WeatherConditionToTextResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherConditionToCodeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherConditionToIconSrcResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLWeatherWindTypeResolver<TParent = any> {
  mph?: WeatherWindToMphResolver<TParent>;
  kph?: WeatherWindToKphResolver<TParent>;
  direction?: WeatherWindToDirectionResolver<TParent>;
}

export interface WeatherWindToMphResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherWindToKphResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherWindToDirectionResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLWeatherWindDirectionTypeResolver<TParent = any> {
  degree?: WeatherWindDirectionToDegreeResolver<TParent>;
  compass?: WeatherWindDirectionToCompassResolver<TParent>;
}

export interface WeatherWindDirectionToDegreeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherWindDirectionToCompassResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLWeatherVelocityTypeResolver<TParent = any> {
  mph?: WeatherVelocityToMphResolver<TParent>;
  kph?: WeatherVelocityToKphResolver<TParent>;
}

export interface WeatherVelocityToMphResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherVelocityToKphResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLWeatherPressureTypeResolver<TParent = any> {
  millibars?: WeatherPressureToMillibarsResolver<TParent>;
  inches?: WeatherPressureToInchesResolver<TParent>;
}

export interface WeatherPressureToMillibarsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherPressureToInchesResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLWeatherRainTypeResolver<TParent = any> {
  millimeters?: WeatherRainToMillimetersResolver<TParent>;
  inches?: WeatherRainToInchesResolver<TParent>;
}

export interface WeatherRainToMillimetersResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WeatherRainToInchesResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}
